# Generated by Django 4.2.7 on 2024-03-26 20:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0010_alter_store_user_id'),
        ('marketplace', '0011_alter_beer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Please enter a description of at least 10 characters')])),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_review', to='marketplace.beer')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='marketplace.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_favourite', to='marketplace.beer')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite', to='marketplace.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('profile_id', 'beer_id'), name='unique_profile_beer'),
        ),
    ]
