# Generated by Django 4.2.7 on 2023-12-07 20:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0009_rename_order_item_orderitem_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Please enter a description of at least 50 characters')])),
                ('rating', models.IntegerField()),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_review', to='marketplace.beer')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='marketplace.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_favourite', to='marketplace.beer')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite', to='marketplace.profile')),
            ],
        ),
    ]
