# Generated by Django 4.2.7 on 2024-02-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('profile_id', 'beer_id'), name='unique_profile_beer'),
        ),
    ]
