# Generated by Django 4.2.7 on 2024-02-26 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions', '0002_favourite_unique_profile_beer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Please enter a description of at least 10 characters')]),
        ),
    ]
