# Generated by Django 4.2.7 on 2023-11-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="phone_number",
            field=models.CharField(max_length=13),
        ),
    ]
