# Generated by Django 4.2.7 on 2023-11-28 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_alter_store_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="store",
            options={"ordering": ["store_name"]},
        ),
    ]
