# Generated by Django 4.2.7 on 2023-12-01 20:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Please enter a description of at least 50 characters')])),
                ('stock_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('beer_image', models.ImageField(upload_to='beer_images')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('abv', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredients', models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Please enter a description of at least 50 characters')])),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_store', to='marketplace.store')),
            ],
        ),
    ]
