# Generated by Django 4.2.7 on 2023-12-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_beer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
