# Generated by Django 4.2.7 on 2023-12-01 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_beer_abv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_order', to='marketplace.beer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='marketplace.order_item')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='marketplace.profile')),
            ],
        ),
    ]
