# Generated by Django 4.2.7 on 2023-12-01 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_order_order_items_order_order_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_item',
            new_name='OrderItem',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_cart', to='marketplace.beer')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cart_items', models.ManyToManyField(to='marketplace.cartitem')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='marketplace.profile')),
            ],
        ),
    ]
