# Generated by Django 4.2.7 on 2024-03-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_store_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='price',
            field=models.TextField(),
        ),
    ]
