# Generated by Django 4.2.7 on 2024-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_beer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
