# Generated by Django 4.2.7 on 2024-03-26 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_beer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'Please enter a description of at least 50 characters')]),
        ),
    ]
