# Generated by Django 4.2.7 on 2024-03-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_beer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='stock_quantity',
            field=models.IntegerField(default=100),
        ),
    ]
